# H2 Database
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:phonestoredb
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true

# Custom Properties
phone-store:
  secret-key: ${JWT_SECRET_KEY:samplesecretkey}
  admin:
    username: ${PHONE_STORE_ADMIN_USERNAME:admin}
    password: ${PHONE_STORE_ADMIN_PASSWORD:pass}
    email: ${PHONE_STORE_ADMIN_EMAIL:admin@email.com}

#logging:
#  level:
#    org:
#      springframework: info